### ISSUE TITLE
f-strings cause an exception

### ISSUE THREAD

**Issue by JaimeLennox** [smarkets/flake8-strict#29]
``Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 429, in _handle_results
    task = get()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() missing 3 required positional arguments: 'type', 'value', and 'context'
``
This was added to lib2to3 here: https://bugs.python.org/issue23894. However, it still seems to be causing problems for flake8-strict.

**Comment by JaimeLennox** [comment]
Requires Python 3.6.2 - not a problem after this.
