### ISSUE TITLE
Flake8 hangs on comma after multiargument parameter

### ISSUE THREAD

**Issue by bkazula** [smarkets/flake8-strict#34]
Hello, I've got code like:
```
def some_method(
            self, first_argument, *args,
):
```
Flake8-strict makes checks hang because of trailing comma in last argument (only with asterisk in the front) with following message:

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 463, in _handle_results
    task = get()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() missing 3 required positional arguments: 'type', 'value', and 'context'
```

I have to add trailing comma as it's required by coding style.

**Comment by JaimeLennox** [comment]
This is a known issue with lib2to3 - unfortunately until this is fixed there, flake8-strict will continue to have this problem. However, I don't believe it forces you to put a trailing comma there (if you are on the latest version).

**Comment by JaimeLennox** [comment]
Fixed by https://github.com/smarkets/flake8-strict/pull/39.
