### ISSUE TITLE
Linter chokes on print statements

### ISSUE THREAD

**Issue by gstalica** [smarkets/flake8-strict#8]
Hey folks,

It seems like there's an issue when a file has a `print` statement in it, written python 2.x-style. The following two files lint (with the appropriate message) properly:

```
from __future__ import print_function

#whatever
print(something)
```

and

```
#whatever
# print something
```

However, when you have this:

```
#whatever
print something
```

It raises the following exception:

```
flake8 test_print.py 
Traceback (most recent call last):
  File "/Users/gina.stalica/projects/kinsights/venv/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/Users/gina.stalica/projects/kinsights/venv/lib/python2.7/site-packages/flake8/main.py", line 36, in main
    report = flake8_style.check_files()
  File "/Users/gina.stalica/projects/kinsights/venv/lib/python2.7/site-packages/flake8/engine.py", line 181, in check_files
    return self._retry_serial(self._styleguide.check_files, paths=paths)
  File "/Users/gina.stalica/projects/kinsights/venv/lib/python2.7/site-packages/flake8/engine.py", line 172, in _retry_serial
    return func(*args, **kwargs)
  File "/Users/gina.stalica/projects/kinsights/venv/lib/python2.7/site-packages/pycodestyle.py", line 1877, in check_files
    runner(path)
  File "/Users/gina.stalica/projects/kinsights/venv/lib/python2.7/site-packages/flake8/engine.py", line 126, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "/Users/gina.stalica/projects/kinsights/venv/lib/python2.7/site-packages/pycodestyle.py", line 1608, in check_all
    self.check_ast()
  File "/Users/gina.stalica/projects/kinsights/venv/lib/python2.7/site-packages/pycodestyle.py", line 1555, in check_ast
    for lineno, offset, text, check in checker.run():
  File "/Users/gina.stalica/projects/kinsights/venv/lib/python2.7/site-packages/flake8_strict.py", line 44, in run
    errors = _process_file(self._filename)
  File "/Users/gina.stalica/projects/kinsights/venv/lib/python2.7/site-packages/flake8_strict.py", line 61, in _process_file
    return _process_code(code)
  File "/Users/gina.stalica/projects/kinsights/venv/lib/python2.7/site-packages/flake8_strict.py", line 65, in _process_code
    tree = _driver.parse_string(code)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=1, value='something', context=(' ', (2, 6))
```

It does look like it is being caused by `lib2to3`, but it sorta defeats the other pieces of the linting chain if a `print` statement will effectively bork the linter :)

Thanks for a great package, guys!

**Comment by jstasiak** [comment]
Hey, thank you for the report and I'm glad you find the project useful. You're right, we don't handle print statements, it's actually documented here: https://github.com/smarkets/flake8-strict/blob/da6f7bafff5c4c8cd9160cf110c9dfc9b1f6b811/README.rst#limitations

It's a conscious decision to not support code with print statements as it makes the linter code simpler while fully supporting our use case (Python 3 code or modern Python 2 code with `from __future__ import print_function` enabled). I'll close this issue as unfortunately there's no intention to change this, I recommend switching to print function if Python 2 has to be used.
