### ISSUE TITLE
lib2to3.pgen2.parse.ParseError processing flake8_strict.py

### ISSUE THREAD

**Issue by jayvdb** [smarkets/flake8-strict#9]
Running flake8-strict on flake8_strict.py:

``` python
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/flake8/main.py", line 36, in main
    report = flake8_style.check_files()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/flake8/engine.py", line 181, in check_files
    return self._retry_serial(self._styleguide.check_files, paths=paths)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/flake8/engine.py", line 172, in _retry_serial
    return func(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pycodestyle.py", line 1875, in check_files
    self.input_dir(path)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pycodestyle.py", line 1911, in input_dir
    runner(os.path.join(root, filename))
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/flake8/engine.py", line 126, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pycodestyle.py", line 1608, in check_all
    self.check_ast()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pycodestyle.py", line 1555, in check_ast
    for lineno, offset, text, check in checker.run():
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/flake8_strict.py", line 44, in run
    errors = _process_file(self._filename)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/flake8_strict.py", line 61, in _process_file
    return _process_code(code)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/flake8_strict.py", line 65, in _process_code
    tree = _driver.parse_string(code)
  File "/opt/python/2.7.9/lib/python2.7/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/opt/python/2.7.9/lib/python2.7/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/opt/python/2.7.9/lib/python2.7/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=8, value=')', context=('\n    ', (24, 4))
```

https://travis-ci.org/jayvdb/flake8-strict/builds/140339633

**Comment by jayvdb** [comment]
#11 says

> The issue that causes this is a limitation of lib2to3 and will be documented separately.

Has that been done? I didnt see a similar problem in http://bugs.python.org

**Comment by jstasiak** [comment]
It's not reported to Python bug tracker, just documented in this project's readme: https://github.com/smarkets/flake8-strict/pull/12

**Comment by jstasiak** [comment]
@jayvdb It's now reported here: http://bugs.python.org/issue27494

**Comment by jayvdb** [comment]
thx.
